# Generated by Django 3.0.5 on 2020-04-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=255, verbose_name='First Name')),
                ('lastname', models.CharField(blank=True, max_length=255, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Addresss')),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('dob', models.IntegerField()),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Company')),
            ],
        ),
    ]
